name: .NET Publish

on:
  release:
    types: [published]
permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Debug --no-restore

    - name: Test
      run: dotnet test --no-build

  version:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_VERSION: ${{ steps.version-tag.outputs.package_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Build Version
        id: version-tag
        run: |
          current_tag=$(git tag --sort=committerdate | tail -1)
          echo current tag: $current_tag
          major=$(echo $current_tag | cut -d "." -f 1 | cut -d "v" -f 2)
          minor=$(echo $current_tag | cut -d "." -f 2)
          patch=$(echo $current_tag | cut -d "." -f 3)
          package_version="$major.$minor.$patch"
          echo "PACKAGE_VERSION=$package_version" >> $GITHUB_OUTPUT
  
  publish:
    needs: 
    - test
    - version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Echo Package Version
      run: echo ${{ needs.version.outputs.PACKAGE_VERSION }}

    - name: Restore
      working-directory: Plumber
      run: dotnet restore

    - name: Build
      working-directory: Plumber
      run: dotnet build --no-restore -c Release -p:Version=${{ needs.version.outputs.PACKAGE_VERSION }}

    - name: Pack
      working-directory: Plumber
      run: dotnet pack -c Release -o nuget -p:PackageVersion=${{ needs.version.outputs.PACKAGE_VERSION }} -p:Version=${{ needs.version.outputs.PACKAGE_VERSION }}

    - name: Publish to nuget.pkg.github.com
      working-directory: Plumber
      run: dotnet nuget push nuget/*.nupkg --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/marklauter/index.json

    - name: Publish to api.nuget.org
      working-directory: Plumber
      run: dotnet nuget push nuget/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
